on: push

name: CI

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make node_modules
      - run: make lint
      - run: make typecheck
      - run: bunx depcheck --ignore-bin-package
      - uses: wagoid/commitlint-github-action@v6
      - run: make build
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: make node_modules
      - name: Simple test
        run: make test
      - name: Build for E2E
        run: make build
      - run: bun link
      - uses: actions/checkout@v4
        with:
          repository: mkobayashime/bookmarklets
          path: repo-bookmarklets
      - name: E2E
        working-directory: ./repo-bookmarklets
        run: |
          bun link --save bookmarklets-cli
          git add .
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git commit --message 'chore: use local package' --allow-empty
          make build
          git add -N .
          git diff --exit-code --stat
