name: Publish Package to npm

on:
  push:
    tags:
      - "v*"
    branches-ignore:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"
      - run: make node_modules
      - run: make build
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
